name: Release

on:
  push:
    branches:
      - 'master'
    paths:
      - 'ncgenes7/VERSION'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: x64
      - name: Install requirements
        run: |
          wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip
          unzip protobuf.zip -d protoc3
          sudo mv protoc3/bin/* /usr/local/bin/
          sudo mv protoc3/include/* /usr/local/include/
          rm -rf protoc3 protobuf.zip
          pip install "tensorflow<1.15"
          pip install -r requirements.txt
          pip install -r requirements_docs.txt
      - name: Create docs html
        run: |
          cd docs_source
          make html
      - name: Commit changes back to repo
        run: |
          PACKAGE_VERSION=`cat ncgenes7/VERSION`
          echo "Found version ${PACKAGE_VERSION}"
          git config --global user.name 'aev-oss-techniscal-user'
          git config --global user.email 'aev-oss-techniscal-user@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.AEV_OSS_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add docs
          git commit -m "autamated docs build for version ${PACKAGE_VERSION}"
          git push origin
      - name: Create release tag
        run: |
          PACKAGE_VERSION=`cat ncgenes7/VERSION`
          git tag v$PACKAGE_VERSION
          git push origin v$PACKAGE_VERSION
          echo "Tag v$PACKAGE_VERSION generated"
